<?php

/**
 * Implements hook_menu().
 */
function mymodule_menu() {
  // Add an administration page for Open Atrium
  $items['mymodule'] = array(
    'title' => 'My Module Page',
    'type' => MENU_CALLBACK,
    'page callback' => 'mymodule_callback',
    'access arguments' => array('access content'),
  );
  return $items;
}

function mymodule_callback() {
  return "Hello World!";
}

/**
 * Implements hook_menu_alter().
 */
function mymodule_menu_alter(&$items) {
  $items['mymodule']['title'] = 'My (modified) Module Page';
}
