<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function mywidget_api_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme()
 */
function mywidget_api_theme() {
  return array(
    'mywidget_api' => array(
      'template'  => 'mywidget_api',
      'path' => drupal_get_path('module', 'mywidget_api') . '/templates',
    ),
  );
}
